### ISSUE TITLE
Currency balance is not displayed while withdrawing

### ISSUE THREAD

**Issue by devluci** [Game-X-Coin/gxc#16]
`gxcli get currency balance gxc.token user game --verbose-balance`

```
[{
    "total": "1123.1111 LUCI@game",
    "balance": "0.0000 LUCI@game",
    "deposit": "37.0000 LUCI@game",
    "withdraw": {
      "quantity": "1086.1111 LUCI@game",
      "scheduled_time": "2019-02-15T08:55:10"
    },
    "options": {
      "frozen": false,
      "whitelist": false
    }
  }
]
```

In verbose-balance mode, when withdraw all token and in progress

`gxcli push action gxc.token withdraw '["user", "37.0000 LUCI@game"]' -p user`

`gxcli get currency balance gxc.token user game --verbose-balance`

Expected Ouput

```
[{
    "total": "1123.1111 LUCI@game",
    "balance": "0.0000 LUCI@game",
    "deposit": "0.0000 LUCI@game",
    "withdraw": {
      "quantity": "1123.1111 LUCI@game",
      "scheduled_time": "2019-02-15T08:55:10"
    },
    "options": {
      "frozen": false,
      "whitelist": false
    }
  }
]
```

Actual output

```
[]
```

It looks like currency balance skipped when balance and deposit are zero, but withdrawing value should be included.

**Comment by conr2d** [comment]
Fixed by Game-X-Coin/gxc.contracts#21
