### ISSUE TITLE
Withdrawing balance can be considered when issuer transfer balance to gxc.null

### ISSUE THREAD

**Issue by devluci** [Game-X-Coin/gxc#17]
When user try to withdraw more than cached balance, issuer should have a permission of revert overdrwan balance and take it.

In current progress, issuer should carry out two actions - `deposit` overdrawn balance and `transfer` it to gxc.null. It looks like can be saved if issuer is able to `transfer` withdrawing balance when not enough balance in deposit.

**Comment by conr2d** [comment]
This issue is related to contracts instead of mainnet. Moved to Game-X-Coin/gxc.contracts.
