### ISSUE TITLE
[testnet] withdrawal is not called automatically.

### ISSUE THREAD

**Issue by realcom** [Game-X-Coin/gxc#33]
Test team call many withdraw request but 9/10 withdrawal request(delayed transaction) is not called.

You can find this issues by checking testuserxxxx(1~5) of Q@catfight, W@catfight, E@catfight, R@catfight.

some examples are

testuser1341 (R@catfight, E@catfight)
testuser3251 (R@catfight, W@catfight)
testuser4135 (E@catfight, R@catfight)
testuser3415 (R@catfight, W@catfight)

**Comment by conr2d** [comment]
This is a contract issue, so moved to [Game-X-Coin/gxc.contracts](https://github.com/Game-X-Coin/gxc.contracts).
